version: "3.9"

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./certs:/root/.simulacrum/certs:ro
    environment:
      - UID
    stdin_open: true
    init: true
    tty: true
    ports:
      - "4000:4000"
      - "4400:4400"
    command: ["sleep", "86400"]
